<?php
/**
 * Security e-Drift — targeted fixes (include from child theme functions.php).
 *
 * Active theme: security-edrift (Kadence child).
 * Copy this file into:
 *   wp-content/themes/security-edrift/functions-edrift-fixes.php
 * Then add ONE line to functions.php (see comment block at bottom of this file,
 * or the matching comment already placed in functions.php in this package).
 *
 * @package security-edrift
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * ISSUE 1 — Wrong Twitter meta handle (@drift)
 *
 * Generated by Yoast SEO from: SEO → Settings → Site features / Social → Twitter
 * (or SEO → Social → Twitter username on older Yoast UIs).
 *
 * No correct Twitter/X handle is defined for this site in options or theme code.
 * Placeholder value was "@drift". Until cleared in wp-admin, strip invalid output.
 *
 * Permanent fix in wp-admin:
 *   Yoast SEO → Settings → Site representation / Social → Twitter username
 *   → delete "@drift" and leave blank → Save.
 */
add_filter( 'wpseo_twitter_site', 'edrift_strip_invalid_twitter_site', 20 );

/**
 * @param string $site Twitter site handle from Yoast.
 * @return string
 */
function edrift_strip_invalid_twitter_site( $site ) {
	$normalized = strtolower( ltrim( trim( (string) $site ), '@' ) );
	if ( '' === $normalized || 'drift' === $normalized ) {
		return '';
	}
	return $site;
}

/**
 * ISSUE 2 — Register Stories page template for classic (Kadence child) theme.
 *
 * page-stories.php also declares Template Name; this filter makes the template
 * explicitly available in the Page Template dropdown.
 *
 * @param array $templates Page templates.
 * @return array
 */
add_filter( 'theme_page_templates', 'edrift_register_stories_page_template' );

/**
 * @param array $templates Templates.
 * @return array
 */
function edrift_register_stories_page_template( $templates ) {
	$templates['page-stories.php'] = __( 'Stories', 'security-edrift' );
	return $templates;
}

/*
 * ---------------------------------------------------------------------------
 * ADD TO functions.php (child theme security-edrift):
 *
 * // Security e-Drift targeted fixes (Twitter meta, Stories template).
 * require_once get_stylesheet_directory() . '/functions-edrift-fixes.php';
 *
 * ISSUE 1 admin location: Yoast SEO → Settings → Social → Twitter → clear @drift
 * ISSUE 2 admin location: Appearance → Menus → Stories item → URL /stories/
 * ISSUE 3: Company field removed from hardcoded homepage/resources subscribe HTML
 *          in site content (not a widget/shortcode). See site/APPLY.md.
 * ---------------------------------------------------------------------------
 */
